### ISSUE TITLE
missing swizzle on matrix multiply

### ISSUE THREAD

**Issue by bo3b** [bo3b/3Dmigoto#10]
Not positive this is a problem, but don't want to lose track of it.

Assembly like:

```
mul r2.xyzw, r0.zzzz, cb1[5].xyzw
mad r2.xyzw, r0.yyyy, cb1[4].xyzw, r2.xyzw
mad r2.xyzw, r0.xxxx, cb1[6].xyzw, r2.xyzw
add r2.xyzw, r2.xywz, cb1[7].xywz
```

Becomes HLSL:

```
  r2.xyzw = g_MVSS_EyeViewToLightTex[1]._m10_m11_m12_m13 * r0.zzzz;
  r2.xyzw = r0.yyyy * g_MVSS_EyeViewToLightTex[1]._m00_m01_m02_m03 + r2.xyzw;
  r2.xyzw = r0.xxxx * g_MVSS_EyeViewToLightTex[1]._m20_m21_m22_m23 + r2.xyzw;
  r2.xyzw = g_MVSS_EyeViewToLightTex[1]._m30_m31_m33_m32 + r2.xywz;
```

Which generates:

```
mul r2.xyzw, r0.zzzz, cb1[5].xywz
mad r2.xyzw, r0.yyyy, cb1[4].xywz, r2.xyzw
mad r2.xyzw, r0.xxxx, cb1[6].xywz, r2.xyzw
add r2.xyzw, r2.xyzw, cb1[7].xywz
```

Where the original has .xyzw, but the final output has some swaps to .xywz

If swizzle is applied to the matrix, it would still compile.
`r2.xyzw = g_MVSS_EyeViewToLightTex[1]._m10_m11_m12_m13.xyzw * r0.zzzz;
`

example in AC4\1567030f987ffd3a-ps_replace.txt

**Comment by bo3b** [comment]
Just saw this again recently in Black Ops 3.  That swap of of the .xyzw to .xywz I think is an fxc compiler bug, I don't think it's legal.

**Comment by DarkStarSword** [comment]
Did it actually cause a problem in Black Ops 3? That looks perfectly legal if the decompiler decided to store the coordinate in r2.xywz, which it is perfectly legal to do since that is effectively just four independent temporary registers and it can choose whatever order it likes. If it screwed up something in an output register that would be a totally different matter since the order is defined for those.

Regardless, this doesn't look like a 3DMigoto bug - can we close this?

**Comment by DarkStarSword** [comment]
Closing this due to lack of response.
