### ISSUE TITLE
Can't simply disable a VB

### ISSUE THREAD

**Issue by leomon32** [bo3b/3Dmigoto#148]
Hello, I'm having an issue, I found a VB value in hunting mode (VS PS CS VB) Last section) that disable an effect in a game, the VB hash is "beaaeeaa" but I don't know what to do with that, I mean I managed to remove some texture and such but I can I remove that vertex buffer entirely or is it impossible with 3Dmitogo ?

I was doing the : 

[ShaderOverridevb0]
hash = beaaeeaa
allow_duplicate_hash=overrule
handling = skip

[ShaderOverrideRippling]
hash = fd570147c961c989
allow_duplicate_hash=overrule
handling = skip

[ShaderOverrideTransparent]
hash = 5ba7ed58f020a2e4
allow_duplicate_hash=overrule
handling = skip

The 2 hash work but obviously not the first one, the latest ones remove the texture but the effect is still present... Can you help me? Thanks!

**Comment by DarkStarSword** [comment]
beaaeeaa is a buffer hash (8 characters), not a shader hash (16 characters), so [ShaderOverridevb0] should be [TextureOverridevb0].

It also needs a checktextureoverride=vb0 in a [ShaderOverride] section for one of the matching pixel or vertex shaders used in each relevant draw call. Considering that you have suppressed the duplicate hash warning I assume someone else has set up the base mod for this game and may have already added it, otherwise you can locate the corresponding shader and add it for yourself.

**Comment by leomon32** [comment]
Thanks a lot, I figured out that I had to activate the log and check everything that corresponds to the values, I found a bunch of shaders and finally found the one that match my expectatiin, thanks a lot!
