### ISSUE TITLE
3DMigotoLoader don't work

### ISSUE THREAD

**Issue by liam063** [bo3b/3Dmigoto#171]
I followed this video: HOW TO MOD GENSHIN (for dummies like me) but when I launch 3DMigotoLoader.exe this message is displayed: waiting for program... and nothing happens please help me
![image_2023-07-19_185815763](https://github.com/bo3b/3Dmigoto/assets/140001705/5965ad48-a5f4-4375-8ad6-9d8cba2ecd42)

**Comment by DarkStarSword** [comment]
Curious, the string "Waiting for program..." is not present in our source code - is this a modified loader?

Actually, even looking at the video you refer to I can see evidence that the loader has been modified - at least superficially:

![image](https://github.com/bo3b/3Dmigoto/assets/379749/bcf34386-7d23-401c-84ee-ea7d164b7de6)

The top line of output has been modified from ours to say "3DMigoto **GIMI** Loader", while ours just says:

	printf("\n------------------------------- 3DMigoto Loader ------------------------------\n\n");

Assuming that whoever has modified it since then has done so with the intent of hiding some of the diagnostic output the most likely explanation for it not loading is that the `target` setting in the d3dx.ini is not set correctly for your install - the video you refer to shows the way to edit this setting, so please double check that.

Of course, since the loader has been modified I can't really guarantee that there isn't some other difference from ours.

**Comment by DarkStarSword** [comment]
Also, you did actually run the game after starting the loader right? It looks like they don't have it set to do that automatically (though the `launch` option in the d3dx.ini can be used to do this automatically), so you have to run it manually.

**Comment by liam063** [comment]
ok i'll try all, thanks

**Comment by hhoneeyy** [comment]
brother, this is the wrong 3dmigoto, create an issue at the the modified fork of it made specifically for genshin and star rail https://github.com/SilentNightSound/GI-Model-Importer
