### ISSUE TITLE
3dmigoto doesnt work on 2d games?

### ISSUE THREAD

**Issue by hhoneeyy** [bo3b/3Dmigoto#172]
i mean, you can kinda tell that from the name 3Dmigoto, but still. i tried it on 3 games, geometry dash, sf30, celeste. nothing. tried both x64 and x32, even tried injecting the d3d11.dll with a dll injector but still nothing

**Comment by DarkStarSword** [comment]
It depends what low level graphics API they use - if they use DirectX 11 3DMigoto should work, if they use something else (e.g. OpenGL, DirectX 9, DirectX 12) it won't. 2D games are less likely to use DirectX 11 than 3D games, but it's certainly not unheard of. You may also find that even if you can get 3DMigoto loaded you may have more limited modding opportunities than a 3D game (e.g. you may find you cannot reliably distinguish between different sprites), but it depends on the game and what you want to use 3DMigoto for.

If 3DMigoto doesn't show the green text I generally check with sysinternals Process Explorer to see the DLLs loaded into the process (enable the lower pane view and set it to show DLLs) to see if d3d11.dll is listed. If it isn't then it's using something other than DirectX 11 and 3DMigoto won't work. If it is listed than it *might* work - however, be aware that third party libraries such as the Steam overlay may also load d3d11.dll even if the game itself is not using it, so seeing it listed is not a guarantee that it is actually used. This can also show if 3DMigoto has been loaded successfully as you would then see two d3d11.dlls in the list, one from the game directory (3DMigoto) and one from system32 (DirectX).

I don't own any of the games you mentioned, so I can't check for myself, but googling:
- Geometry Dash runs on the open source Cocos2D engine. Glancing through the code it appears to use OpenGL / WebGL, not DirectX, so 3DMigoto won't work.
- Street Fighter 30th Anniversary: There is virtually zero chance that this uses DirectX 11 - more likely an emulator of some ancient graphics hardware of the original arcade cabinets. Even the most recent title included in this bundle predates DirectX 11 by a full decade. Unless the emulator they used itself uses DirectX 11 (doubtful, but not unheard of - e.g. Dolphin uses DirectX and works with 3DMigoto) 3DMigoto won't work.
- Celeste uses MonoGame, which uses XNA, not DirectX. I've never looked into XNA in great detail - it is a Microsoft technology so might use DirectX under the hood, but what I'm reading suggests that it's an alternative to DirectX rather than a layer on top of it, and if it does use DirectX internally I see some mention of DX9, not DX11, so 3DMigoto is unlikely to work.

In some cases it may be possible to make a game using an old / different graphics API compatible with 3DMigoto by using additional software that emulates the graphics API that the game is using with DirectX 11, e.g. dgVoodo can emulate older DirectX versions and output DX11 which then can work with 3DMigoto. I'm not super familiar with these tools, but you don't need to look very far through https://helixmod.blogspot.com to find some examples. I don't know if this would work in any of the games you are looking at.
