### ISSUE TITLE
help my lumine is a little broken 

### ISSUE THREAD

**Issue by Clover696969** [bo3b/3Dmigoto#176]
ive been trying to mod genshin with 3dmigoto (as of 4.1 update) and ive successfuly got a lots of new skins for my characters. But my Lumine is kinda broken. When i tried to mod her a new skin (from gamebanana), her body vanished and i can only see her face. the cutscenes look cursed af... 
![Screenshot (153)](https://github.com/bo3b/3Dmigoto/assets/147912719/99e9590e-d923-4f88-b015-7a281cf269a8)
ive also tried reinstalling and even changing the mod file but it is NOT working. and yes, ive also used the 4.1update trouble shooter which i also got from gamebanana. pls help and advice me if i can do anything to fix this.

**Comment by DarkStarSword** [comment]
3DMigoto is a generic DX11 graphics modding tool used in hundreds of games, but we (as in the 3DMigoto developers) are not directly involved in many of those games - you are probably better off asking this question in the modding community for the specific game you are having issues with.

Genshin Impact modding community uses the the Anime Game Modding Group discord, which is probably the best place to ask:
https://discord.com/invite/agmg

Alternatively the 3DMigoto fork used by the Genshin Impact modding team is here:
https://github.com/SilentNightSound/GI-Model-Importer

**Comment by Clover696969** [comment]
srry about that😅😅, im still new to modding and didnt know about the correct place to ask for issues

**Comment by DarkStarSword** [comment]
It might also be worth adding a little footnote that historically when Chiri gave the original source code to Bo3b to be made public, that he indicated that he wanted anyone to be able to do whatever they wanted with it, potentially including commercial use. As such the original release of 3DMigoto was actually released under the MIT license, though as time went on we brought in certain dependencies (most notably Nektra's in process hooking library) that required us to re-license under the GPLv3, and we did try to dual-license for a while but are now exclusively GPLv3.

**Comment by nekosumi** [comment]
Hello @DarkStarSword!

If I'm to be honest, something doesn't add up here. It's hard to call GIMI a fork if even the author of the fork didn't click `Fork` on `bo3b/3Dmigoto`. This behavior seems quite unfair and unethical. The purpose of GPLv3 is to ensure users the freedom to use, study, share, and modify software, while also ensuring that these freedoms are preserved for all copies of the software, even if it is modified. As far as I know, GPLv3 requires documenting changes, although it doesn't specify exactly how these changes should be documented.
The number of changes in the fork is irrelevant; a derivative work should still be open-source. Regarding the CC BY-NC-ND 4.0 license on gamebanana.com, this license is assigned to the GIMI fork, leading to another violation of the licensing rules. Generally, GameBanana operates on very unconventional principles. Additionally, the website itself has a weak security system, but to stray from the topic, the GameBanana administration and SilentNightSound seem to lack a proper understanding of licensing rules. They do not attempt to solve any issues related to licensing, instead miring in their own quagmire. I have more information on this matter.

Best regards!

**Comment by DarkStarSword** [comment]
OK, that makes it pretty clear that you are not here in good faith, and just want to use the license agreements as a tool to further your own agenda - an agenda that as a libertarian I STRONGLY disagree with, and I will have no further part of your nonsense.

**Comment by nekosumi** [comment]
@DarkStarSword, it would be appropriate to explain this "nonsense" and present your own position, rather than running away. Another degenerate. I wonder if you also fap to 10-year-old anime girls (;

Do what you want, you will be turning in hell for the deeds you commit. I also advise you to go to church.
God will certainly not be proud of you supporting degeneracy. For me, you're simply avoiding the conversation because you're fully aware of the honest truth in what I wrote. Or are you just a fucking pedophile without dignity? I wish you, bastard, end up under a bridge.

### I wrote honestly about what I think. If you don't respect my opinion, I won't respect you as a person. Thats all (:

**Comment by nekosumi** [comment]
I'm also sending a little bonus from me (:
Have a nice night or day, who knows what time it is in your fucking brothel.

https://github.com/bo3b/3Dmigoto/assets/43447005/bdc58c5b-b2df-410a-88bb-75d2f140fd70

**Comment by nekosumi** [comment]
@DarkStarSword , may Lord Jesus keep you in His care, guiding you with His divine light and blessing you with His endless grace. May your faith be a beacon in times of darkness, leading you towards a path of righteousness and peace.

In the face of dark and challenging issues such as pedophilia, faith in God can become a refuge for many, offering solace, strength, and hope for healing. Faith teaches us about love for our neighbor, compassion, and the protection of the most vulnerable, especially children, who are most at risk of harm. It reminds us of the moral responsibility of every individual to guard the innocence and dignity of every person.

![image](https://github.com/bo3b/3Dmigoto/assets/43447005/57820514-5090-478f-baae-188e2186831b)

**Comment by DarkStarSword** [comment]
If you want my position, look up what "libertarian" means. I won't engage in further conversation with you because I believe you will will just try to use anything I say to further your own agenda. At this point you have devolved to using unfounded personal attacks, which are absolutely not acceptable.

**Comment by bo3b** [comment]
Just noting that I agree completely with your edits.

**Comment by bo3b** [comment]
@nekosumi is obviously another _fake_ Christian.  Doing evil in the name of Jesus, no matter how well intentioned, was never what Jesus said.  I grew up Christian, and don't understand how people can misunderstand the message this badly.

I've reported him for abuse and blocked his new harassment account as well.

**Comment by DarkStarSword** [comment]
Thanks Bo3b, I just saw the insanity in my inbox and and am glad you already took care of reporting + blocking it.

**Comment by DarkStarSword** [comment]
[<img src="http://www.psychalive.org/wp-content/uploads/2013/01/are_you_a_narcissist-1.jpg" />](https://www.psychalive.org/narcissist-infographic/)

**Comment by bo3b** [comment]
Yeah, these people who are _always_ right, no matter what. \<sigh\>  If he'd stopped at the initial stupidity that would have been alright, but he just had to make a mess.  Github has deleted both of his accounts, and all his posts, because they were waaay over the line.

One thing to note- I set 3Dmigoto to block anyone from posting, commenting, or making new issues; If they have a new account.  I assume this guy will continue to create spam accounts, and figured it wouldn't hurt to have a cooldown. Currently set for a month, if you think that is too long, please feel free to edit it as you see best.

**Comment by DarkStarSword** [comment]
The funny thing is that he questioned what I meant by "nonsense", and all of his actions since then have very clearly demonstrated exactly the nonsense I meant by that.

**Comment by DarkStarSword** [comment]
The source code to the GIMI fork has now been published in a topic branch on this repo, and the license agreement listed on GameBanana has been corrected to GPLv3, so as far as I am concerned the GIMI fork is now in full compliance with the 3DMigoto license agreement.
