### ISSUE TITLE
Anti-cheat game crash

### ISSUE THREAD

**Issue by Matx23** [bo3b/3Dmigoto#348]
Solved: Epic Version has anti-cheat problem hoyo ,version had no issues

The Anti-cheat close my game 

also after game closes d3d11.dll get deleted(??)

**Comment by DarkStarSword** [comment]
No idea which game you are referring to, but since you mentioned Epic I assume you are probably talking about Easy Anti Cheat. EAC is known to block 3DMigoto (not because we are targeted, but rather because it blocks anything it doesn't recognise).

This is not something we can fix on our side, if it is important to you please feel free to take it up with Epic/EAC.
