### ISSUE TITLE
Disassembler producing double negatives

### ISSUE THREAD

**Issue by DarkStarSword** [bo3b/3Dmigoto#37]
This disassembler is creating double negatives in some cases, e.g. in the Batman tile lighting compute shaders we see (this is from eb8c3e5e00a6c476-cs.txt):

          mov r19.yzw, l(0,--0.444036931,00.0614555776,--0.229850411)
          mov r23.xyz, l(-0.255772650,--2.148475353E-008,--0.0497171432,0)
          mov r24.xyz, l(-0.888073862,--7.763788545E-008,--0.459700823,0)
          mov r25.xyz, l(-0.888073862,--7.763788545E-008,--0.459700823,0)

Examining the original .bin and reasm.bin shows that these should only be single negatives - the original .bin has the negative value and the reasm.bin has 0.

I suspect this is likely to be an issue in the literal fixup code (but have not ran these through just the MS disassembler without the fixup yet so have not confirmed).

**Comment by DarkStarSword** [comment]
The "...,00.061..." also looks suspect actually - is it just duplicating the first character in the fixed up literal?

**Comment by DarkStarSword** [comment]
Pretty sure I found & fixed the bug. Testing now to confirm...

**Comment by Flugan** [comment]
Where did you fix the bug outside the shader I don't see any code changes. Although the bug might not be worth fixing as it was quick to work around.

**Comment by DarkStarSword** [comment]
"DarkStarSword closed this in 2ecd9e1 19 hours ago" - that links to the commit with the code changes.

**Comment by Flugan** [comment]
Had to figure out why this happened in the first place and the answer is pretty much in fxc for the shader that bugged. It appears that multi literals almost always have spaces which is why this was detected just now. Your solution obviously removes all spaces if literals need fixing while keeping them otherwise. Given that we know the nature of the problem we could check if there is a space and do +2 and +1 otherwise. In the end the bug is fixed and what remains is if we want consistent use of spaces. This is an oxymoron as the original problem is inconsistent use of spaces but that for different literals coming from MS disassembler.

**Comment by DarkStarSword** [comment]
It would be nice to be consistent with the spaces - I was wondering if we could just insert an extra space at that point since we know we will have stripped one if there was one, or as you say we could check if there was already a space there and make an appropriate decision based on that.

I'd rate this as a wishlist item now - the serious bug is fixed and cleaning the inconsistent whitespace is just a bit of polish.

**Comment by Flugan** [comment]
Updated code, unable to compile and test (running VS2015)

**Comment by DarkStarSword** [comment]
What's the issue preventing you from compiling and testing it? I had to fix an issue in that commit that broke the build, but once fixed it seems to work fine.

**Comment by Flugan** [comment]
I currently have Community version of Visual Studio 2015. I've never had VS2013 on this machine. I find having multiple copies of VS to be a bit messy. Also at that time I couldn't find VS2013 as the site had been replaced with links to VS2015. I'm not saying the link does not exist as I quickly googled and found VS2013. VS2015 can compile VS2013 projects if the VS2013 toolset is installed. This should explain why I couldn't compile and test the code. I'm avoiding what I consider a mess but my ability to work on 3DMigoto is severely limited. All my other solutions have been migrated to VS2015 so I kind of need VS2015 as downgrading is very hard. One question is if 3DMigoto should switch to VS2015 and I see no real reason but I would personally do it as I am otherwise unable to build.

**Comment by DarkStarSword** [comment]
I'm currently using VS2015 for my dev builds of 3DMigoto, but I do still have VS2013 installed as well, which might explain why that is working. I haven't checked what toolchain runs when I run the publish.bat to release a build.
