### ISSUE TITLE
ISGN and OSGN handling in the assembler

### ISSUE THREAD

**Issue by Flugan** [bo3b/3Dmigoto#38]
This has been mentioned but I thought it deserved a separate topic.

thanx to
https://raw.githubusercontent.com/bkaradzic/bgfx/0f9d6cefa59ba5a005c4ed7a88ac414a580ae6b3/src/shader_dxbc.cpp
and
https://raw.githubusercontent.com/bkaradzic/bgfx/0f9d6cefa59ba5a005c4ed7a88ac414a580ae6b3/src/shader_dxbc.h

the high level data structure is known. Mapping the commented Input/Output signatures into binary will require more work. Should files missing signatures be allowed to compile and if so should it fall back on using the current method of reusing the signatures from the original shader. If not the assembler can rebuild the binary straight from the shader assembly file. Appears to have confirmed that SHDR is for SM4 and SHEX is for SM5.

Adding http://timjones.tw/blog/archive/2015/09/02/parsing-direct3d-shader-bytecode to the mix should clear things up.

I keep wondering how people manage to figure things out without documentation at the same time that I just was informed that opcodes are pretty well documented in the WDK which I never installed.

**Comment by DarkStarSword** [comment]
I have a slight preference to using only the information in the assembly file rather than reusing sections from the original binary - I've just added a feature to inject new custom shaders and currently that only works with HLSL because of the requirement to have an original binary for the assembly shaders. I'm not sure if anyone will ever want to inject a new assembly shader, but maybe if it was copied partially/fully from an existing assembly shader...

The only risk at the moment is if someone has used an assembly shader and removed/corrupted the comment, which will work in the current version but not once we start parsing the comment. I don't think we should worry about this - I doubt that anyone will have done this, and if it has happened they can continue to use an old version or fix the comment.

**Comment by Flugan** [comment]
Assembler has not been widely used in 3DMigoto compared to HLSL. When  it has been used I don't think the signature comments have been altered or stripped. When disabling shaders sometimes the whole file has been nuked leaving some simple ASM code replacing the content. This is following guides from helixmod. As I see it the commented input and output signature segments have become required as we start parsing these sections in the assembler. You can still strip all assembler code and replace with stubs as long as the signatures are kept or altered but not removed. I won't be able to produce ISGN and OSGN out of thin air.

**Comment by DarkStarSword** [comment]
This is now implemented in commit f1ade955ec6f3e368b82c40961d122d2878c359f

The parser is currently in cmd_Decompiler, which manufactures a new shader binary containing ISGN, ISG1, OSGN, OSG5, OSG1, PCSG, PSG1 sections based on what it finds in the comment blocks, and an empty SHDR / SHEX section depending on the shader model. This is passed to the assembler as though it was the original binary which will then replace the SHDR/SHEX section and fill in the hash.

Currently this is restricted to cmd_Decompiler while it undergoes testing (I haven't run it in game yet). Later we can move the code into the assembler itself.

**Comment by DarkStarSword** [comment]
This is now fully integrated into 3DMigoto 1.2.65, with a config option to enable the signature parsing (mostly in case an existing fix has corrupted the comment blocks)
