### ISSUE TITLE
Using unicode characters in the first comment line results in a crash.

### ISSUE THREAD

**Issue by oomek** [bo3b/3Dmigoto#42]
I mentioned that a while ago on the forum. When one of the Polish characters like ąęćśżźółń is used in the first and commented line of a shader the game (Dirt 3) crashes during hunting when cycling through vertex shaders.

**Comment by bo3b** [comment]
This will be in the Overlay code, where it picks up the first line and draws that to screen.  

I'm fairly certain that SpriteFont can handle unicode, so we must be doing a bad conversion.

**Comment by DarkStarSword** [comment]
What's the encoding of the file? cp1252, utf8 or something else?

Note that we probably need to make an executive decision here for what all shaders should be encoded if we don't want a nasty encoding guessing heuristic (and we should use utf8 - it's a superset and backwards compatible with 7-bit ASCII and isn't tied to whatever language the OS happens to be set to. cp1252 and all the rest of the 8-bit code pages are hacks - they are backwards compatible with 7-bit ASCII, but they aren't compatible with each other, so they are all terrible choices. utf16/32 is OK, but they are not backwards compatible with anything and they really shouldn't ever have been used for user files)

**Comment by bo3b** [comment]
I'm almost certain that anything we generate are encoded in UTF-8, no BOM.

**Comment by DarkStarSword** [comment]
Fixed in https://github.com/bo3b/3Dmigoto/commit/a8c8bdd37b5dfd1c3b904410d62f968aeb60a192 , but note that this does not add support for the characters you mentioned in the overlay (they are not in the font we use) - it fixes the UTF8 conversion and the crash.


I'm going to repeat this rant here (it's not aimed at anyone here. Maybe Microsoft):

As a side note - in this case it is borderline acceptable to store the tag line as UTF16 because that's what the API expects it to be in, and we don't otherwise do anything with it, but the simple truth is that the API has been poorly designed as there is NEVER a good reason to use UTF16 - it is literally the worst of all worlds and should be considered harmful:

It is NOT fixed code point width like UTF32 (it's more like UTF8 in that regards, but most people don't realise this) and requires special handling like this to make work properly - just using wide characters does not magically give the program unicode support. It bloats everything, and is not an optimal size for CPU registers to work with.  There are only a few countries where text even ends up smaller in UTF16 than it does in UTF8, but that isn't even an advantage because any form of compression offers better results again.

7-bit ASCII, UTF8 and UTF32 are the only sensible encodings (and UTF32 should only be used when it immediate access to characters by index is required). Everything else is a mistake.

Windows has forced UTF16 on us, but that doesn't mean we should embrace it.
