### ISSUE TITLE
Feature Request: Expand OSD usage

### ISSUE THREAD

**Issue by DJ-RK** [bo3b/3Dmigoto#46]
Hey guys. Again, another idea that's probably been thought of, but here goes. I was wondering if the on-screen display could be expanded to be used outside of hunting modes? 

For example, when changing presets to allow a specified message to be displayed, like "HUD 25% depth" or "____ shaders disabled". Be great if we could have operators that could display values like %x would display the value assigned to the X parameter, or %c for convergence, etc, and even better (if possible) to allow those values to be mathematically modified, eg. "HUD at <%x \* 100> percent" would display "HUD at 25 percent" assuming X to be 0.25.

Another possibility (and I think I might've even seen some discussion of this) would be to possibly be used inside a shader to display an output of a constant buffer or register value. This, however, I am certain would be a greater task and should be considered a separate (and secondary) request to the first.

**Comment by DarkStarSword** [comment]
It's possible to do a lot of this inside custom shaders nowadays without requiring any dedicated support from 3DMigoto - you can use my constant buffer debug shader as a starting point to render text from a geometry shader on the GPU. It's a little clumsy to output strings (I don't know of a good way to do string processing in HLSL), but you can output a series of characters, integers and floating point numbers. There is a limit to the number of characters a single invocation of the geometry shader can produce, but the geometry shader can be invoked multiple times (as it is in the debug shader - each line is one invocation). Custom shaders also present the possibility to render graphics rather than just text if someone wanted something that looked polished. We probably do need to pass additional inputs into shaders - things like the number of milliseconds that have passed since the game was launched that the shader can use to track how long it has displayed for and hide itself automatically (hint: use a UAV to store state on the GPU between runs).

We could maybe expand the OSD in 3DMigoto itself to make that easier, but we would need very clear goals in mind if we don't want to wind up implementing yet another widget toolkit as we make it more and more flexible (I think every programmer does this at some stage... the good ones realise why they should not have).

> Another possibility (and I think I might've even seen some discussion of this) would be to possibly be used inside a shader to display an output of a constant buffer or register value. This, however, I am certain would be a greater task and should be considered a separate (and secondary) request to the first.

My constant buffer (not limited to use with constant buffers) debug shader is available here to do this:
https://github.com/DarkStarSword/3d-fixes/tree/master/custom_shader_cb_live_view

**Comment by masterotaku** [comment]
Now that there is a new way of showing text when realoading shaders and hunting, I'd like to bring this to attention again.

For a while I've been including a bunch of graphics mods in my fixes (mostly toggles or presets for post processing effects), and it can be hard to know what the current state of the IniParams is when I start pressing hotkeys ingame.

As one possibility, the text configuration could be similar to this, if it could be attached to a hotkey:

;Bloom.
[Key7]
general_text = "Bloom state: "
Key = 2
type = cycle
z1 = 0, 0.5, 1
text = "disabled", "half bloom", "normal bloom"
transition = 300
transition_type = cosine

Having a text variable that in this case cycles alongside the "z1" values, giving users (or us hackers if we use the text for switching different experiments ingame) the ability to know the current state of things.

Another possibility would be attaching text values to specific variable values (per variable) outside of the hotkeys section. So if for example a hotkey changes multiple variables, multiple lines of text would be shown on screen. But I don't know what would be the best way to show this in "d3dx.ini".

**Comment by DarkStarSword** [comment]
I'm not opposed to this, but given that it is already possible to do something more flexible than anything 3DMigoto could ever do using only custom shaders and custom resources it is a lower priority. I need to make a better (much simpler) example, and I'm still working out the best way to do some things, but take a look at how I display the auto-convergence state and popout bias value in Life Is Strange: Before the Storm, excerpts below:

d3dx.ini definition for a buffer to hold any state you need (e.g. the timestamp of when you started displaying a given HUD element):

    [ResourceAutoConvergenceState]
    type = RWStructuredBuffer
    ;
    ; data= sets the initial state of the buffer - the size of the buffer is
    ; automatically calculated from this, offering an alternative to manually
    ; specifying stride and array - for a structured buffer stride will be set to
    ; the buffer size, and array will be 1.
    ;
    ; Specifying the format inline here instead of in a separate format= line makes
    ; it only apply to parsing this line, leaving the actual buffer format as
    ; UNKNOWN, which is necessary for structured buffers.
    ;
    ; Pass hex literalls for parameters that aren't floats, e.g. You can stop the
    ; auto-convergence HUD from showing up on launch by changing the initial state
    ; of prev_auto_convergence_enabled (8th field, a boolean) to 0xffffffff.
    data = R32_FLOAT 0 0 0 0 0 0 0 0x00000000 0

The HLSL definition of the same buffer - you can see how above we had 9 entries in data=, and here we have 9 as well - count the float4 as 4 entries, the rest are 1 each. You can set this buffer up to hold whatever state you need - I've got a few things for auto-convergence here that aren't relevant to you, but you will need last_adjust_time if you want the HUD to timeout, and something along the lines of prev_auto_convergence_enabled so you can detect when whatever you are interested in changes:

    struct auto_convergence_state {
            float4 last_convergence;
            float user_popout_bias;
            float last_adjust_time;
            bool show_hud;
            bool prev_auto_convergence_enabled;
            bool no_z_buffer;
    };

Implement the logic that tracks state with a compute or pixel shader (other shader types can only read the buffer, not write to it). In the case of LiSBtS I used my auto-convergence pixel shader for this purpose, but generally I'd actually recommend using a compute shader:

    [CustomShaderAutoConvergence]
    vs = ShaderFixes/full_screen.hlsl
    ps = ShaderFixes/auto_convergence.hlsl

    ; UAV slots allow the state buffer to be modified. I'm using u1 here
    ; because in pixel shaders these are shared with render targets and I'm
    ; writing to o0 - normally you would use cs-u0 instead:
    ps-u1 = ResourceAutoConvergenceState
    post ps-u1 = null

    ; Pass in the time since launch so the shader can record when it triggered
    ; a HUD message:
    x3 = time

    ; Or "Dispatch = 1, 1, 1" if using a compute shader:
    Draw = 4, 0

    ; Use my debug shaders if you need to examine the state buffer:
    ;ResourceDebugBuf = ResourceAutoConvergenceState

Inside the actual shader define which register has the state buffer (and include the HLSL struct definition above this - I have that in a separate file since I need it from two shaders):

    RWStructuredBuffer<struct auto_convergence_state> state : register(u1);

Then implement some logic to control the HUD in the shader's main routine, e.g.

	if (state[0].prev_auto_convergence_enabled != auto_convergence_enabled) {
		state[0].last_adjust_time = time;
		state[0].show_hud = true;
		state[0].prev_auto_convergence_enabled = auto_convergence_enabled;
	}

Add a font definition to d3dx.ini:

    [ResourceAutoConvergenceFont]
    ; Note that this font has the size of each character embedded in the unused
    ; space of the final character, which the geometry shader uses to render each
    ; character the correct width. This font was generated with gen_bm_font.py,
    ; then converted to DDS (because our PNG loading seems to be broken o_O):
    filename = ShaderFixes\LiberationSans-Bold.dds

The actual .dds file I've been using is here, or you can use my python script to create your own: 
https://github.com/DarkStarSword/3d-fixes/raw/master/custom_shader_cb_live_view/ShaderFixes/LiberationSans-Bold.dds

Add a definition for the HUD shaders to the d3dx.ini, that binds the state resource to a gs-t* slot (gs-t113 in this case):

    [CustomShaderAutoConvergenceHUD]
    ; The vertex shader passes draw indexes to the geometry shader:
    vs = ShaderFixes/auto_convergence_hud_vs.hlsl
    ; The geometry shader generates the text for a given draw index:
    gs = ShaderFixes/auto_convergence_hud_gs.hlsl
    ; The pixel shader draws the font:
    ps = ShaderFixes/auto_convergence_hud_ps.hlsl
    cull = none
    ; Enable alpha blending. To change the text colour, edit the pixel shader:
    blend = add one inv_src_alpha
    ; Use points as the primitive from the vertex shader to the geometry shader:
    topology = point_list
    run = CommandListUnbindAllRenderTargets
    o0 = set_viewport no_view_cache bb
    ; Pass the auto-convergence state to the geometry shader:
    gs-t113 = ResourceAutoConvergenceState
    post gs-t113 = null
    ; Font is passed into the pixel shader (to draw it) *and* the geometry shader
    ; (as the character sizes are encoded in the final character of the font):
    gs-t100 = ResourceAutoConvergenceFont
    ps-t100 = ResourceAutoConvergenceFont
    post gs-t100 = null
    post ps-t100 = null
    ; Change this number to set how many lines of text may be drawn:
    draw = 1, 0

Grab my HUD shaders from LISBtS:

https://github.com/DarkStarSword/3d-fixes/blob/master/Life%20is%20Strange%20-%20Before%20the%20Storm/ShaderFixes/auto_convergence_hud_vs.hlsl
https://github.com/DarkStarSword/3d-fixes/blob/master/Life%20is%20Strange%20-%20Before%20the%20Storm/ShaderFixes/auto_convergence_hud_gs.hlsl
https://github.com/DarkStarSword/3d-fixes/blob/master/Life%20is%20Strange%20-%20Before%20the%20Storm/ShaderFixes/auto_convergence_hud_ps.hlsl

Then customise the main() function of the geometry shader to render text. Note that HLSL doesn't have a native string type (don't be deceived by the documentation - that is purely for debugging), so printing strings is a little awkward. In LISBtS I've got a bunch of emit_char() calls to print them one character at a time, but I have found two better ways since then, which you can see in action in the below shader - the static strings are in "static const uint FOO[] = {'F', 'o', 'o', ' ', 'b', 'a', 'r'};" at the top of the file, then a macro EMIT_CHAR_ARRAY is used to display them. 3DMigoto can also pass a string to the shader inside a buffer (e.g. initialised with data=, or potentially written from another shader), and this shader displays them via the print_string_buffer() function:

    https://github.com/DarkStarSword/3d-fixes/blob/master/stereo_buffer_tests/ShaderFixes/buffer_test_gs.hlsl

Once again a final reminder - the geometry shader can only produce a pretty limited number of characters per invocation, so if you find some text being cut off that is why. You can raise the number in the "draw = 1, 0" line to invoke it multiple times, and have each invocation responsible for some text, using the input[0].idx to work out which invocation is being run (e.g. my debug shader that this came from uses that to render four floating point numbers per invocation).


This is certainly complicated, so I'm not ruling out doing something simpler in 3DMigoto later, but it is worth noting that my LISBtS HUD would not have been possible with a simple built-in notification method in 3DMigotoo, because it needed to display the popout-bias, which 3DMigoto has no knowledge of. This is why I'm reluctant to start adding HUD support to 3DMigoto - I know UIs, and what starts out simple will grow and grow and grow and grow with feature creep and before you know it we've gone and reinvented QT, only we don't yet handle all the edge cases like non-English text or accessibility devices.

**Comment by DarkStarSword** [comment]
1.3.7 should make this a lot easier if you just want to display an overlay for a few seconds after a key press. You can now run a command list from a key section, which allows you to set an ini param to the time. Set a different ini param to the time in the custom HUD shader and you can compare the two inside the shader and display a message if it is within a few seconds.

This means you don't need the state buffer or the second custom shader any more (unless you are doing something particularly complicated).

    [KeyActivateSomething]
    key = z
    ; Key sections can't set an iniparam to the time, but a command list can:
    run = CommandListUpdateActivationTime

    [CommandListUpdateActivationTime]
    x = time

    [CustomShaderOverlay]
    vs = ShaderFixes/custom_overlay.hlsl
    gs = ShaderFixes/custom_overlay.hlsl
    ps = ShaderFixes/custom_overlay.hlsl
    y = time
    ...

And inside the shader:

    if (IniParams[0].y - IniParams[0].x < 2000) {
    	// Display some overlay
    }

**Comment by DarkStarSword** [comment]
I have written a custom help & notification text shader that can be used for this purpose. The shader as it stands doesn't support formatting modifiers like %x, but it takes a buffer filled with arbitrary NULL terminated ASCII text and you could populate that using another shader if you want to fill it out dynamically, or modify the shader to generate whatever text you wish instead of printing out the buffer (the shader includes integer and floating point formatting functions that you can use if you want).

The shader can be found at:
https://github.com/DarkStarSword/3d-fixes/tree/master/custom_shader_help_text

Post on Help Text:
https://forums.geforce.com/default/topic/685657/3d-vision/3dmigoto-now-open-source-/post/5336166/#5336166

Post on using this to show notification text from a key binding or other command list:
https://forums.geforce.com/default/topic/685657/3d-vision/3dmigoto-now-open-source-/post/5339106/#5339106

At this stage given the flexibility these shaders allow I don't see any reason to expand 3DMigoto's OSD, so I'm going to close this issue. If someone strongly disagrees with this you can reopen it.

**Comment by bo3b** [comment]
Adding the new direct links to the broken and horrible NVidia forums.  But we can now get links to specific posts. I don't believe the forums are indexed by google anymore. NVidia's built in search is broken and unusable. I found these by reading big chunks of the main thread.

Post on Help Text: https://www.nvidia.com/en-us/geforce/forums/3d-vision/41/169637/3dmigoto-now-open-source/1242524/

Post on show notification on keybinding: https://www.nvidia.com/en-us/geforce/forums/3d-vision/41/169637/3dmigoto-now-open-source/1242521/#5336166
