### ISSUE TITLE
3dvision2sbsvs SLI Scaling

### ISSUE THREAD

**Issue by DavG** [bo3b/3Dmigoto#48]
Hello,
First, thanks a lot for this Wrapper and the 3DVision SBS/TB Shaders :)

I found a problem with the 3dvision2sbsvs.hlsl when SLI is enabled : i lose totally the SLI scaling.

I have made my tests with Metro 2033 (non Redux) and Max Payne 3.
The SLI Scaling in 3D "vanilla" is good, GPUs Load are ~95-99%.

When I enable this shader, both GPUs Load are 50%.
If i comment all the **pos** lines, the scaling is as good as in Vanilla (so the problem is not the pixel shader, but the vertex shader), but of course i lost the feature.

I think each card is waiting the other one.
Do you have an idea how to enable SLI scaling with this shader ?

Thanks in advance

**Comment by bo3b** [comment]
Thanks for that report and especially narrowing it down to VS.

DarkStarSword is the expert here with the SBS shader, and is getting an SLI setup shortly, so hopefully he'll get a chance to take a look.

**Comment by DarkStarSword** [comment]
I don't believe the issue will be the vertex shader - this will be the same SLI bandwidth bottleneck issue discussed in https://github.com/bo3b/3Dmigoto/issues/53 .

The reason killing the VS like that appears to improve performance is subtle, and you have to know a little about how CPUs and GPUs work to understand that. Once we initiate the stereo2mono copy it will start copying data between GPUs, which will take some time to complete. In the meantime other things can continue running on the GPU so long as they don't depend on that data - as soon as we run something that depends on that data the GPU will stall waiting for it to finish copying. If you disable the pos output from the vertex shader then you have completely removed the dependency on that data, not because the vertex shader depends on it, but because the pixel shader depends on it and you have eliminated all pixel shader invocations.

**Comment by DarkStarSword** [comment]
3DMigoto 1.3.11 now includes an SLI optimised version of the 3DVision2SBS shader that automatically downscales prior to the stereo2mono pass.
