### ISSUE TITLE
Please allow commads duplicates in ini

### ISSUE THREAD

**Issue by oomek** [bo3b/3Dmigoto#55]
This would help to organise ini into logical blocks. Ini parser could just join the parameters from repeated commands in the order of occurrence.

**Comment by DarkStarSword** [comment]
I originally didn't want this because duplicated sections were often bugs, but I agree that it could be useful in some cases.

The biggest problem we will have supporting multiple sections is that we have no provably correct way to order the commands across them - e.g. the 3DVision2SBS custom shader should always run after any other shaders that render custom info to the screen (otherwise it will not convert the results of those to SBS and we will get half the result in one eye and half in the other) and there may be similar ordering requirements between other custom shaders, and any custom shaders that take an input need to come before shaders that clear those inputs... unless we wanted that resource cleared, then used as an output, then used as an input... This isn't something that we can have 3DMigoto easily guess, because no matter what heuristics we try to use there will be cases where it is wrong.

On the other hand, maybe I'm overthinking it, and just doing it in the order that the commands appear in the d3dx.ini globally would suffice for most cases.

I need to think about this one.

**Comment by oomek** [comment]
It would help in situations when you want to disable for example all the fixes and leave only one for debug purposes. If it may cause more troubles than benefits don't bother.

**Comment by DarkStarSword** [comment]
I'm thinking if we do this we could use an 'allow_duplicate_section=true' flag that has to be present in all of the duplicated sections - that way the user has explicitly acknowledged that it is intended and when they come back to it five months later that will provide a hint that they may need to look elsewhere in the file to see the rest of the settings that may affect the behaviour.

And we won't try to second guess any ordering between sections - that will just occur from top of the file to bottom for the pre command list, followed by the original draw/present call, followed by top of the file to bottom for the post command list (the fact that a post command in an earlier section will happen after a pre command in a later section may be a little surprising, but that's just an extension of the existing behaviour and part of the point of requiring the user to explicitly acknowledge this).

**Comment by DarkStarSword** [comment]
There's a bit of extra complexity here that we'd need to sort out - ShaderOverride sections can be duplicated by either name or hash. Currently we disallow both, but if we were to implement this we would need to handle all four permutations, including merging settings that don't fall into the command list category (settings in the command list category are already permitted to be duplicates) - I think we should not consider implementing this until we have replaced the ini parsing API (which is a low priority).

**Comment by oomek** [comment]
That's exactly what I was thinking, a flag allowing for duplicates. That includes [Present] I hope.

**Comment by DarkStarSword** [comment]
We don't support this yet, but 3DMigoto 1.2.64 has an entirely new ini parser written by yours truly (something like 200x faster than the old one - this had become a significant problem in Dreamfall Chapters that was taking upwards of two minutes to read the file). This is one of the necessary steps towards supporting duplicate sections in the future, if we end up deciding to do so.

**Comment by oomek** [comment]
I'm happy that you are thinking on implementing it. As always great job.

**Comment by DarkStarSword** [comment]
1.2.65 now supports ShaderOverride sections with duplicate hashes:
- "allow_duplicate_hash=true" must be present in all sections with a duplicate hash to protect against adding a duplicate without meaning to
- The section name still has to be unique. The idea is that if these sections are generated by a tool it would name them the same each time, thereby triggering a warning if it adds the same section multiple times. If you're using this to group sections logically you could add something in the section name indicating what logical group it is a part of.
- Command lists will be appended. I strongly urge against adding anything to these that could depend on the order they are run in between sections. It is not top to bottom, and I'm not guaranteeing that it won't change in the future (if you want to know it should be the same order the shaderoverride sections are parsed in - sorted alphabetically case insensitive).
- Duplicate non-command list options will *not* be warned about, and whichever is parsed last will be used. You acknowledge this when you use the feature ;-)


At this stage I am not considering allowing ShaderOverride or TextureOverride to have duplicate section names, but I am considering this as a possibility for [Present].

**Comment by DarkStarSword** [comment]
1.3.10 now supports duplicate sections indirectly via the new ability to include additional config files - these included files are permitted to append to global sections such as [Present], and can serve to keep the configuration more organised at the same time. The order these files are included will ultimately determine the order the commands are run in the [Present] command list. When the recursive_include mechanism is in use the order is not explicit, so 3DMigoto will sort the files and directories alphabetically (case insensitive) to try to at least give a consistent order between runs.

Any section that is prefixed (ShaderOverride*, TextureOverride*, Resource*, etc) will be namespaced based on which configuration file it is in, so these names do not need to be unique across the entire config - just whichever file they are in.

The allow_duplicate_hash option in ShaderOverride sections can now be set to "overrule", which will trump the "all sections must opt in" rule and disable the duplicate hash warning for that shader.

TextureOverride sections can now have a duplicate hash, provided that one of the match_* options is used - either for fuzzy resource description matching, the new draw context matching in 1.3.10, or if nothing else, match_priority=n will allow them to have duplicate hashes because that defines an ordering between these used by checktextureoverride and texture filtering.

You can read more about the modular config support in the release notes - I think it might be a good fit for your modding efforts:
https://forums.geforce.com/default/topic/685657/3d-vision/3dmigoto-now-open-source-/post/5325230/#5325230

I think this is probably enough to close this - the main d3dx.ini still can't have duplicate section names though, so if you feel this is insufficient feel free to re-open the issue.
