### ISSUE TITLE
XXXXXXXXX_bad.txt 

### ISSUE THREAD

**Issue by ayuanx** [bo3b/3Dmigoto#58]
> If you want to disable a specific shader or skip it, you can add a file to ShaderFixes like 7ca36f0ff0ee6ea9-ps_bad.txt.

It seems this functions isn't working any more?

**Comment by bo3b** [comment]
Code is still there, and it should work to prevent loading.

You can also rename the front of it, like xxx7ca36f0ff0ee6ea9-ps_replace.txt

If you mean skip the shader drawing instead of loading, you want to use the skip option for a shader in the d3dx.ini.

**Comment by ayuanx** [comment]
Hi bo3b,

Maybe I misunderstood the purpose of "_bad.txt".
Does it mean to skip processing this txt file, or to inhibit the original shader of the game matching this hash from rendering?
For the latter, the contents of the "_bad.txt" could be completely empty.

**Comment by DarkStarSword** [comment]
AFIK _bad.txt is to prevent decompiled shaders from loading if they suffer from decompiler bugs causing rendering issues, or to otherwise mark a shader as one that should not be fixed so that the original shader from the game will be used.

I'm not sure we actually need explicit code for this - personally, my scripts use slightly different naming scheme for these cases: ~failed to mark a decompiled shader as failing an automated compile test, and ~bad to (manually) mark one that caused an issue that should not be fixed. These are ignored by virtue of the fact that they don't match the filenames that 3DMigoto looks for.

**Comment by ayuanx** [comment]
Yeah, I agree. This "_bad.txt" thing is confusing. Because if we don't want to load this txt, we can simply move it to another folder, which is much faster than renaming.

I think it would be better to have a simple way to disable an original shader from rendering if we know the hash of that shader, e.g. by renaming the txt.

**Comment by DarkStarSword** [comment]
We already have a simple way to disable shaders in the d3dx.ini that Bo3b mentioned above, and there is no way we want to complicate our shader loading functions any more by looking for yet another filename variant (these are already ridiculously complex). As a user I think you can just ignore the existence of the _bad.txt altogether, and as developers Bo3b or I might remove the code behind it some day when we get around to cleaning up those functions.

How did you find out about the existence of that anyway? Is it in our documentation somewhere, or did you look at the code?

**Comment by ayuanx** [comment]
"_bad.txt" is mentioned in Wiki -> Misc Notes.

I didn't know the method of disabling specific shader in "d3dx.ini". I think you should put it in Wiki for quick reference.
