### ISSUE TITLE
Fixing shadows and lights that are only seen by one eye

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [bo3b/3Dmigoto#59]
I want to fix shadows that are not on the right surface and lights that are only seen by one eye in "Homefront Revolution".

1. Where do I find a tutorial for fixing shadows on the wrong 3D-plane?
2. How do I copy light that can only be seen with one eye to the other one?

PS: For those that don't like "Homefront Revolution", don't tell me.

**Comment by ErfolgreichCharismatisch** [comment]
Don't everybody speak up at once!

**Comment by bo3b** [comment]
Interesting strategy to directly insult the people that you are asking for help.

**Comment by ErfolgreichCharismatisch** [comment]
Stop looking for attention bo3b and make room for those that know their stuff.

**Comment by DarkStarSword** [comment]
Bo3b knows his stuff, but you would know that already if you had found his school first and done his lessons, or noticed that he is one of the main authors of 3DMigoto.

Shadows are among the hardest effects to fix and you should not be starting with them. You are asking the wrong questions and revealing your ignorance, but I'll answer anyway:

1. There isn't one, because there isn't just one way in which shadows can be broken. There are examples - try studying the fixes of other games that use the same engine. Homefront Revolution is CryEngine 4, so study other fixes for that engine such as Ryse: Son of Rome. But a history lesson - the Ryse fix is based off my Lichdom Battlemage fix, which was for CryEngine 3, and the first game where I cracked CryEngine shadows, so the commits in the git history for that has some notes that may be of interest. As I understand it CryEngine 4 added some more complications, so you may need to study both.

2. You don't - you figure out why they are only showing in one eye in the first place and fix that. There is no one answer here as there are various things that could go wrong, such as not having stereo compute shaders enabled, driver heuristics only running a shader in one eye or a render target not being correctly stereoised.

I've had some very needy students in the past, and your second comment reveals that you may be another of these, and to be quite frank I do not have time to handhold you, especially as I am not in a good place mentally right now.

Do the lessons, understand how fixing games works, fix some easier effects and make sure you understand those before you start on shadows, study the examples, revise linear algebra and homogeneous (4D) coordinate transformations, read the notes in my commit history and anything posted on the geforce.com 3D Vision forums related to this engine and fixing games more generally, then and only then if you have a specific question you may ask it.

But don't ask here - ask on the shaderhacker school thread on the 3D Vision forums so that the other shaderhackers can help. If you ask here you will only get the attention of the 3DMigoto authors.

**Comment by DarkStarSword** [comment]
This video might be of interest for shadows, but is not CryEngine specific:
https://www.youtube.com/watch?v=GssPDoVtQfA

**Comment by helifax** [comment]
[quote]
I've had some very needy students in the past that took up a whole buttload of my time and ended up contributing absolutely nothing back to the community, and your second comment reveals that you may be another of these, and to be quite frank I do not have time to handhold you, especially as I am not in a good place mentally right now.
[/quote]

I hope I wasn't one of them;)
I did learn a lot and still learning!
I am still trying my best to fix DX11 games and so on;) I really hope you'll feel better soon, my friend!
A lot of people over 3D Vision forums is missing you already!

**Comment by DarkStarSword** [comment]
Oh no @helifax, you have given a huge amount back to the community, and you always show a willingness to learn - I have no problem with helping you, and hopefully once I'm recovered from all this mess that I have been dealing with in my personal life I hope to come back to the community and help you with that Frostbite engine :-)

No, the student I'm referring to took a whole bunch of lessons from me in private to learn how to fix Unity games, and it was a very painstaking process getting him to the point where he could use my scripts taking up a whole lot of my time and then... nothing.

**Comment by helifax** [comment]
:( Oh damn... The Unity stuff again... as bad as the damn Frostbite engine stuff:( (Specifics upon specifics:( )
I do hope you will feel better very soon! 
(
And I do mean it! From personal experience I know how it is, I had to cancel my first wedding 1 week before... you could imagine the stress and emotional impact, not to mention the mental one... I don't presume to know what you go through, but... we are all people, more than meat and bones ;) Dark Souls got it right... "You Died !" Some parts of us die every day, but we must always find a way to prevail! And in the end it all gets more than you wanted! (I am married now to the most wonderful person.. but SHH!! ^_^) I just takes a bloody long time to get there though... :(

If there is  any way I can help - any shape or form - please let me know!

I would like to have a chat with you as well, if you are interested as well - outside of fixing stereo 3D games, or the "community service"! You are an awesome Intellectual person and it really pains me to see a person in a "depression state" when they have this huge potential! Both as a human being and as an intellectual and valued human being!!! (Sadly not a lot "of us" around, and is frustrating!) 
)
Please don't get it this the wrong way:) Just let me know if you want a quick and "painless" chat about something else (graphics related and awesome as well;) )

Thank you for everything,
Helifax
