### ISSUE TITLE
Wrong object creation?

### ISSUE THREAD

**Issue by bo3b** [bo3b/3Dmigoto#65]
HackerDevice constructor is:

`HackerDevice::HackerDevice(ID3D11Device *pDevice, ID3D11DeviceContext *pContext)
	 : ID3D11Device(),
	mStereoHandle(0), mStereoResourceView(0), mStereoTexture(0),
	mIniResourceView(0), mIniTexture(0),
	mZBufferResourceView(0), 
	mHackerContext(0), mHackerSwapChain(0), mHackerDXGIDevice1(0)
{
	mOrigDevice = pDevice;
	mRealOrigDevice = pDevice;
	mOrigContext = pContext;
}
`

Occurs to me that is probably wrong, because the ": ID3D11Device()" is not valid.  Not sure what that does, but that is not how any ID3D11Device is ever created, it's not a C++ object.

I think we have several of these mistaken constructors lurking around.

**Comment by ColAngel** [comment]
ID3D11Device(), hmm actually it is a valid c++ syntax to call the parent constructor. (The line is not necessary there because it is default one, but it is not an error or missconfiguration). However, there is no constructor in d3d11.h (the one in sdk) for this class so i assume the default one is used..., so i think it is ok this way at least here. (the proper device is anyway already created and is passed to the hackerdevice via parameter in constructor)

P.S.: Maybe it is the way the factory creates the a device (???) and updates the data with setter functions (SetPrivateData) or something like that.

**Comment by bo3b** [comment]
Yup, it's the right syntax, but my concern is that an ID3D11Device is not a true C++ object.  It's some freaky object-like thing Microsoft made, that uses QueryInterface to access it's members.

An ID3D11Device can only be properly created with an API: D3D11CreateDevice.  So not a constructor of any form.

So, calling through to that doesn't really make sense, because it's not a real object, and I'm not exactly sure what happens.  My best guess is that it ought to not call through to that, because our object is HackerDevice, and even though it is a subclass of ID3D11Device, it's only a subclass for the purposes of providing direct API replacements.

This is part of the hacking/modding, where it's not totally obvious what the right choice is.

**Comment by ColAngel** [comment]
tried to find out the stuff... it seems the call does not create an object it just calls the constructor of the parent class the actuall object construction occurs in the HackerDevice class (compiler mixes anyway everything together). Maybe we should simply try to remove the code line and see what happens :-) not pretty scientific approach but somethimes the empirical approch is the best. My guess (based on c++ class hierarchy) it will cause no problems. (the complier sees only the class definition of the ID3DDevice and its parents) But I also never worked with COM-Interfaces and fake objects before.

**Comment by DarkStarSword** [comment]
It's an interface, so the constructor should be empty.

**Comment by DarkStarSword** [comment]
I'm closing this - I am quite convinced that we are doing the right thing and reading a few MSDN pages on COM confirm that this is just bog standard OO Interfaces - they haven't done anything funky or unusual here aside from QueryInterface, but even though that causes us some pain it does makes a lot of sense really once you realise that these are all interfaces to a larger object and are not concrete implementations in themselves.

Summary: It won't matter if we do or do not call the interface constructor because it won't do anything.
